export const FETCH_COMMITMENT = 'FETCH_COMMITMENTS';
export const FETCH_COMMITMENT_FAILED = 'FETCH_COMMITMENTS_FAILED';
export const FETCH_COMMITMENT_SUCCESS = 'FETCH_COMMITMENTS_SUCCESS';

export const FETCH_COMMITMENT_MILESTONE = 'FETCH_COMMITMENT_MILESTONE';
export const FETCH_COMMITMENT_MILESTONE_SUCCESS = 'FETCH_COMMITMENT_MILESTONE_SUCCESS';
export const FETCH_COMMITMENT_MILESTONE_FAILED = 'FETCH_COMMITMENT_MILESTONE_FAILED';

export const FETCH_MILESTONE_LIST = 'FETCH_MILESTONE_LIST';
export const FETCH_MILESTONE_LIST_SUCCESS = 'FETCH_MILESTONE_LIST_SUCCESS';
export const FETCH_MILESTONE_LIST_FAILED = 'FETCH_MILESTONE_LIST_FAILED';
