export const REGISTERING_COMPANY = 'REGISTERING_COMPANY';
export const REGISTERING_COMPANY_FAILED = 'REGISTERING_COMPANY_FAILED';
export const REGISTERING_COMPANY_SUCCESS = 'REGISTERING_COMPANY_SUCCESS';
