export const FETCH_BLOGS = 'FETCH_BLOGS';
export const FETCH_BLOGS_SUCCESS = 'FETCH_BLOGS_SUCCESS';
export const FETCH_BLOGS_FAILED = 'FETCH_BLOGS_FAILED';

export const FETCH_SINGLE_BLOG = 'FETCH_SINGLE_BLOG';
export const FETCH_SINGLE_BLOG_SUCCESS = 'FETCH_SINGLE_BLOG_SUCCESS';
export const FETCH_SINGLE_BLOG_FAILED = 'FETCH_SINGLE_BLOG_FAILED';
