export const SIGNUP_FOR_NEWSLETTER = 'SIGNUP_FOR_NEWSLETTER';
export const SIGNUP_FOR_NEWSLETTER_FAILED = 'SIGNUP_FOR_NEWSLETTER_FAILED';
export const SIGNUP_FOR_NEWSLETTER_SUCCESS = 'SIGNUP_FOR_NEWSLETTER_SUCCESS';
